/**
 * `PageNotFoundError` error.
 *
 * PageNotFoundError wraps errors generated by node-oauth.  By wrapping these
 * objects, error messages can be formatted in a manner that aids in debugging
 * OAuth issues.
 *
 * @api public
 */
function PageNotFoundError(message) {
  Error.call(this);
  Error.captureStackTrace(this, arguments.callee);
  this.name = 'PageNotFoundError';
  this.message = message;
};

/**
 * Inherit from `Error`.
 */
PageNotFoundError.prototype.__proto__ = Error.prototype;

/**
 * Returns a string representing the error.
 *
 * @return {String}
 * @api public
 */
PageNotFoundError.prototype.toString = function() {
  return this.message;
}

/**
 * Expose `PageNotFoundError`.
 */
module.exports = PageNotFoundError;
